POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Camry",
  "year": 2018,
  "mileage": 50000,
  "lng": 0,
  "lat": 0,
  "price": 10000
}

### Approve an existing report
PATCH http://localhost:3000/reports/3
Content-Type: application/json

{
  "approved": false
}
